version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.7
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make setup
      - run: make test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
